name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: creating output dirs
        run: mkdir -p out/production && mkdir -p out/artifacts
      - name: compiling classes 
        run: javac -d out/production src/Main.java src/PingCheckServer.java
      - name: building jar
        run: jar cmf META-INF/MANIFEST.MF out/artifacts/pingServer.jar src/Main.java src/PingCheckServer.java
      - name: Upload jar to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pingServer.jar
          path: out/artifacts/*
